# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: imagegen.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'imagegen.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eimagegen.proto\"-\n\x0cImageRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\r\n\x05steps\x18\x02 \x01(\x05\"5\n\rImageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0cimage_base64\x18\x02 \x01(\t2A\n\x0fImageGenService\x12.\n\rGenerateImage\x12\r.ImageRequest\x1a\x0e.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imagegen_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=18
  _globals['_IMAGEREQUEST']._serialized_end=63
  _globals['_IMAGERESPONSE']._serialized_start=65
  _globals['_IMAGERESPONSE']._serialized_end=118
  _globals['_IMAGEGENSERVICE']._serialized_start=120
  _globals['_IMAGEGENSERVICE']._serialized_end=185
# @@protoc_insertion_point(module_scope)
